version: 2.1
orbs:
  cypress: cypress-io/cypress@3.4.0
executor: cypress/default
workflows:
  build:
    jobs:
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          name: Run Cypress tests
          start-command: npm start
          cypress-command: 'npx cypress run'
          parallelism: 3