version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      # "cypress" is the name of the imported orb
      # "run" is the name of the job defined in Cypress orb
      - cypress/run:
          no-workspace: true
          name: Run Cypress tests
          start: npm start
          wait-on: 'http://localhost:8080'
          report: true
          tags: circleCI