name: ci-nightly
on:
  schedule:
    # runs tests every day at 4am
    - cron: '0 4 * * *'
jobs:
  nightly:
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        
      - name: Cypress nightly tests 🌃
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          start: npm start
          wait-on: 'http://localhost:8080'
          tag: Github Nightly
        env:
          # pass the record key as environment variable
          # during this CI step
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}