name: ci
on: [push]
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          record: true
          parallel: true
          start: npm start
          wait-on: 'http://localhost:8080'
          tag: Github
        env:
          # pass the record key as environment variable
          # during this CI step
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}