name: ci
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            ~/.npm
          key: dependencies-v1-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Start the app
        run: npm start &

      - name: Wait for url
        run: npx wait-on http://localhost:8080

      - name: Run Cypress tests
        run: npm run cy:run -- --record
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}